/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import trabajo2.Ciudad;

/**
 *
 * @author usuario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        setLookAndFeel();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public JPanel getPanelGrafico() {
        return panelGraficador;
    }

    public JButton getBotonPararTaxis() {
        return botonPararTaxis;
    }

    public JButton getBotonGraficar() {
        return botonGraficar;
    }

    public JComboBox getComboxCiudad() {
        return comboxCiudad;
    }

    public JComboBox getComboxEscenarios() {
        return comboxEscenario;
    }

    public Object getCiudadSeleccionada() {
        return comboxCiudad.getSelectedItem();
    }

    public JButton getBotonGraficarTaxis() {
        return botonGraficarTaxis;
    }

    public JButton getBotonRutaCorta() {
        return botonRutaCorta;
    }

    public void setLabelCiudad(String ciudad) {
        labelCiudad.setText(ciudad);
    }

    public void setLabelEscenario(Integer escenario) {
        labelEscenario.setText(escenario.toString());
    }

    public void setLabelTaxis(Integer taxis) {
        labelTaxis.setText(taxis.toString());
    }

    public int getEscenarioSeleccionado() {
        return comboxEscenario.getSelectedIndex() + 1;
    }

    public void fillCiudadCombox(HashMap<Integer, Ciudad> ciudades) {
        comboxCiudad.removeAllItems();
        for (Map.Entry<Integer, Ciudad> registro : ciudades.entrySet()) {
            Integer integer = registro.getKey();
            Ciudad ciudad = registro.getValue();
            comboxCiudad.addItem(ciudad);
        }
    }

    public void fillComboxEscenarios(int numeroEscenarios) {
        comboxEscenario.removeAllItems();
        for (int i = 1; i <= numeroEscenarios; i++) {
            comboxEscenario.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel0 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboxCiudad = new javax.swing.JComboBox();
        comboxEscenario = new javax.swing.JComboBox();
        botonGraficar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonGraficarTaxis = new javax.swing.JButton();
        botonPararTaxis = new javax.swing.JButton();
        botonRutaCorta = new javax.swing.JButton();
        botonAtravesarEdificio = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelGraficador = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEscenario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTaxis = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numEdifAtrav = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numHuecAtrav = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Segundo Trabajo de BD 2  - Graficación de ciudades");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficación de ciudades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ciudad:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Escenario:");

        comboxCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboxEscenario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonGraficar.setText("Graficar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxEscenario, 0, 143, Short.MAX_VALUE)
                            .addComponent(comboxCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGraficar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboxEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGraficar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Taxis", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        botonGraficarTaxis.setText("Graficar taxis");

        botonPararTaxis.setText("Parar");

        botonRutaCorta.setText("Recoger usuario (5)");

        botonAtravesarEdificio.setText("Recoger usuario (4)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonGraficarTaxis, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(botonPararTaxis, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonAtravesarEdificio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRutaCorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGraficarTaxis)
                    .addComponent(botonPararTaxis))
                .addGap(18, 18, 18)
                .addComponent(botonAtravesarEdificio)
                .addGap(18, 18, 18)
                .addComponent(botonRutaCorta)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Jpanel0Layout = new javax.swing.GroupLayout(Jpanel0);
        Jpanel0.setLayout(Jpanel0Layout);
        Jpanel0Layout.setHorizontalGroup(
            Jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jpanel0Layout.setVerticalGroup(
            Jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel0Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGraficador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grafico de la ciudad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelGraficador.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Ciudad: ");
        jPanel3.add(jLabel1);

        labelCiudad.setText("Niguna");
        jPanel3.add(labelCiudad);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Escenario: ");
        jPanel3.add(jLabel2);

        labelEscenario.setText("Ninguno");
        jPanel3.add(labelEscenario);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Taxis:");
        jPanel3.add(jLabel5);

        labelTaxis.setText("0");
        jPanel3.add(labelTaxis);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Edificios atravesados:");
        jPanel3.add(jLabel6);

        numEdifAtrav.setText("0");
        jPanel3.add(numEdifAtrav);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Huecos atravesados:");
        jPanel3.add(jLabel7);

        numHuecAtrav.setText("0");
        jPanel3.add(numHuecAtrav);

        panelGraficador.add(jPanel3, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Jpanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelGraficador, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jpanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGraficador, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel0;
    private javax.swing.JButton botonAtravesarEdificio;
    private javax.swing.JButton botonGraficar;
    private javax.swing.JButton botonGraficarTaxis;
    private javax.swing.JButton botonPararTaxis;
    private javax.swing.JButton botonRutaCorta;
    private javax.swing.JComboBox comboxCiudad;
    private javax.swing.JComboBox comboxEscenario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelEscenario;
    private javax.swing.JLabel labelTaxis;
    private javax.swing.JLabel numEdifAtrav;
    private javax.swing.JLabel numHuecAtrav;
    private javax.swing.JPanel panelGraficador;
    // End of variables declaration//GEN-END:variables

    public int getNumEdifAtrav() {
        return Integer.parseInt(numEdifAtrav.getText());
    }

    public void setNumEdifAtrav(int numEdifAtrav) {
        this.numEdifAtrav.setText(String.valueOf(numEdifAtrav));
    }

    public int getNumHuecAtrav() {
        return Integer.parseInt(numHuecAtrav.getText());
    }

    public void setNumHuecAtrav(int numHuecAtrav) {
        this.numHuecAtrav.setText(String.valueOf(numHuecAtrav));
    }

    public JButton getBotonAtravesarEdificio() {
        return botonAtravesarEdificio;
    }

    private void setLookAndFeel() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

}
